//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPK.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CurrentLink {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CurrentLink() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPK.Data.Resources.CurrentLink", typeof(CurrentLink).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/dmnhanvien/create.
        /// </summary>
        public static string AddDmNhanVien {
            get {
                return ResourceManager.GetString("AddDmNhanVien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/dmvethang/create.
        /// </summary>
        public static string AddDmVeThang {
            get {
                return ResourceManager.GetString("AddDmVeThang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/nhanvien/create.
        /// </summary>
        public static string AddNhanVien {
            get {
                return ResourceManager.GetString("AddNhanVien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/applicationUser/getall.
        /// </summary>
        public static string ApplicationUser {
            get {
                return ResourceManager.GetString("ApplicationUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/dmnhanvien/delete.
        /// </summary>
        public static string DeleteDmNhanVien {
            get {
                return ResourceManager.GetString("DeleteDmNhanVien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/dmvethang/delete.
        /// </summary>
        public static string DeleteDmVeThang {
            get {
                return ResourceManager.GetString("DeleteDmVeThang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/dmnhanvien/deletemulti.
        /// </summary>
        public static string DeleteMultiDmNhanVien {
            get {
                return ResourceManager.GetString("DeleteMultiDmNhanVien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/dmvethang/deletemulti.
        /// </summary>
        public static string DeleteMultiDmVeThang {
            get {
                return ResourceManager.GetString("DeleteMultiDmVeThang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/nhanvien/deletemulti.
        /// </summary>
        public static string DeleteMultiNhanVien {
            get {
                return ResourceManager.GetString("DeleteMultiNhanVien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/the/deletemulti.
        /// </summary>
        public static string DeleteMultiThe {
            get {
                return ResourceManager.GetString("DeleteMultiThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/nhanvien/delete.
        /// </summary>
        public static string DeleteNhanVien {
            get {
                return ResourceManager.GetString("DeleteNhanVien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/the/delete.
        /// </summary>
        public static string DeleteThe {
            get {
                return ResourceManager.GetString("DeleteThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/dmnhanvien/getall.
        /// </summary>
        public static string GetAllDmNhanVien {
            get {
                return ResourceManager.GetString("GetAllDmNhanVien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/dmvethang/getall.
        /// </summary>
        public static string GetAllDmVeThang {
            get {
                return ResourceManager.GetString("GetAllDmVeThang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/nhanvien/getall.
        /// </summary>
        public static string GetAllNhanVien {
            get {
                return ResourceManager.GetString("GetAllNhanVien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/the/getall.
        /// </summary>
        public static string GetAllThe {
            get {
                return ResourceManager.GetString("GetAllThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/dmnhanvien/getbyid.
        /// </summary>
        public static string GetByIdDmNhanVien {
            get {
                return ResourceManager.GetString("GetByIdDmNhanVien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/dmvethang/getbyid.
        /// </summary>
        public static string GetByIdDmVeThang {
            get {
                return ResourceManager.GetString("GetByIdDmVeThang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/nhanvien/getbyid.
        /// </summary>
        public static string GetByIdNhanVien {
            get {
                return ResourceManager.GetString("GetByIdNhanVien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/giahan/thongkengay.
        /// </summary>
        public static string ThongKeGiaHan {
            get {
                return ResourceManager.GetString("ThongKeGiaHan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/ra/thongkengay.
        /// </summary>
        public static string ThongKeNhanh {
            get {
                return ResourceManager.GetString("ThongKeNhanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/dmnhanvien/update.
        /// </summary>
        public static string UpdateDmNhanVien {
            get {
                return ResourceManager.GetString("UpdateDmNhanVien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/dmvethang/update.
        /// </summary>
        public static string UpdateDmVeThang {
            get {
                return ResourceManager.GetString("UpdateDmVeThang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/nhanvien/update.
        /// </summary>
        public static string UpdateNhanVien {
            get {
                return ResourceManager.GetString("UpdateNhanVien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/the/update.
        /// </summary>
        public static string UpdateThe {
            get {
                return ResourceManager.GetString("UpdateThe", resourceCulture);
            }
        }
    }
}
